// src/types.ts

// --- Enums ---

export enum Difficulty {
  Easy = "Easy",
  Medium = "Medium",
  Hard = "Hard",
  Expert = "Expert",
}

export enum Taxonomy {
  Remembering = "Remembering",
  Understanding = "Understanding",
  Applying = "Applying",
  Analyzing = "Analyzing",
  Evaluating = "Evaluating",
  Creating = "Creating",
}

export enum AiProvider {
  Gemini = "Gemini",
  Groq = "Groq",
  OpenRouter = "OpenRouter",
}

export enum Role {
  Faculty = 'faculty',
  Student = 'student',
}

// --- Navigation Types ---

export type View =
  | 'landing'
  | 'auth'
  | 'emailVerification'
  | 'idVerification'
  // Main Views
  | 'dashboard'
  | 'career' // Dedicated Career Page
  | 'authAction' // Handling Firebase Actions (Verify Email, Reset Pwd)
  | 'content'
  | 'network'
  | 'integrity'
  // Sub Views / Actions
  | 'generator'
  | 'results'
  | 'manualCreator'
  | 'test'
  | 'studentLogin'
  | 'testResults'
  | 'testHistory'
  | 'notifications'
  | 'testAnalytics'
  | 'profile'
  // Legacy / Redirections
  | 'studentPortal'
  | 'facultyPortal'
  | 'following'
  | 'followers'
  | 'connect'
  | 'myBanks'
  | 'createBank'
  | 'editBank'
  | 'certificate'
  | 'about'
  | 'contact'
  | 'privacy'
  | 'terms'
  | 'team';

// --- User & Social Interfaces ---

export interface AppUser {
  id: string; // Firebase UID
  username: string;
  name: string;
  email: string;
  role: Role;
  collegeName: string;
  country: string;
  state: string;
  district: string;
  facultyId: string;
  isIdVerified: boolean;

  // Legacy arrays (kept for backward compat or immediate checks, but deprecated in favor of Counts + Connections collection)
  following: string[];
  followers?: string[];
  facultyConnections?: string[];

  // Social 2.0
  followersCount: number;
  followingCount: number;
  avatarUrl?: string; // DiceBear URL
  cortexMetrics?: CortexMetrics;
  careerGoal?: CareerGoal;
}

export interface SocialConnection {
  id: string;
  userA: string; // One of the users
  userB: string; // The other user
  createdAt: string; // ISO String
}

export interface ConnectionRequest {
  id: string;
  fromFacultyId: string;
  fromFacultyName: string;
  fromFacultyCollege: string;
  toFacultyId: string;
  status: 'pending' | 'accepted' | 'rejected';
}

export interface FollowRequest {
  id: string;
  fromUserId: string;
  fromUserName?: string;
  fromUserEmail?: string;
  toUserId: string;
  status: 'pending' | 'accepted_by_receiver' | 'pending_auto_followback' | 'rejected' | 'accepted';
  autoGenerated?: boolean;
  createdAt: string;
}

export interface ChatMessage {
  id: string;
  chatId: string;
  senderId: string;
  senderName: string;
  text?: string;
  imageUrl?: string;
  timestamp: string | Date;
}

// --- Content & Test Interfaces ---

export interface MCQ {
  question: string;
  options: string[];
  answer: string;
  explanation?: string;
  correctAnswer?: string; // Fallback for some AI models
}

export interface FormState {
  topic: string;
  difficulty: Difficulty;
  taxonomy: Taxonomy;
  questions: number;
  studyMaterial: string;
  imageData?: {
    mimeType: string;
    data: string;
  } | null;
  aiProvider: AiProvider;
}

export interface CustomFormField {
  label: string;
  required?: boolean;
}

export interface Test {
  id: string;
  facultyId: string;
  title: string;
  durationMinutes: number;
  questions: MCQ[];
  studentFieldsMode: 'default' | 'custom';
  customStudentFields: CustomFormField[];
  endDate: string | null;
  disqualifiedStudents?: string[];
  // Advanced Controls
  shuffleQuestions?: boolean;
  shuffleOptions?: boolean;
  attemptLimit?: number;
  allowSkip?: boolean;
}

export interface GeneratedMcqSet {
  id: string;
  facultyId: string;
  timestamp: Date;
  mcqs: MCQ[];
}

export interface QuestionBank {
  id: string;
  facultyId: string;
  title: string;
  description?: string;
  questions: MCQ[];
  tags: string[];
  createdAt: string; // ISO String
  updatedAt: string; // ISO String
  isPublic?: boolean;
}

// --- Student Execution Interfaces ---

export interface Student {
  name: string;
  registrationNumber: string;
  branch: string;
  section: string;
  customData?: { [key: string]: string };
}

export interface TestAttempt {
  id: string;
  testId: string;
  studentId: string;
  testTitle: string;
  student: Student;
  score: number;
  totalQuestions: number;
  answers: (string | null)[];
  date: Date; // Unified date field (replaced timestamp)
  violations: number;
  questions?: MCQ[]; // Snapshot of questions at time of attempt
}

// --- System Interfaces ---

export interface AppNotification {
  id: string;
  studentId: string; // Recipient
  studentEmail: string;
  facultyId: string; // Sender
  facultyName: string;
  facultyUsername?: string;

  // Dynamic Content
  type?: 'test_invite' | 'message' | 'alert';
  title?: string;
  message?: string;
  test?: Test; // Optional (only for test_invite)

  status: 'new' | 'read' | 'ignored';
  timestamp?: string; // ISO String
  actionTimestamp?: string;
}

export interface ViolationAlert {
  id: string;
  studentId: string;
  studentEmail: string;
  facultyId: string;
  testId: string;
  testTitle: string;
  timestamp: string;
  status: 'pending' | 'resolved';
}

// --- Cortex 2.0 Interfaces ---

export interface TopicPerformance {
  topic: string;
  score: number; // 0-100
  attempts: number;
  lastAttemptDate: string;
}

export interface CortexMetrics {
  strongTopics: string[]; // Score > 80%
  weakTopics: string[];   // Score < 60%
  topicMap: Record<string, TopicPerformance>;
  learningTrend: 'improving' | 'declining' | 'stable';
  recommendedDifficulty: Difficulty;
}

export interface PersonalizedPlan {
  focusTopics: string[];
  suggestedAction: 'review_basics' | 'practice_hard' | 'attempt_new_topic';
  reasoning: string;
}

// --- Career Mapping Interfaces ---

export interface Skill {
  name: string;
  proficiency: number; // 0-100
  category: 'technical' | 'soft' | 'domain';
}

export interface CareerRole {
  id: string;
  title: string;
  description: string;
  requiredSkills: { name: string; level: number }[]; // Level 0-100
  averageSalary: string;
  demandLevel: 'high' | 'medium' | 'low';
  category?: string; // e.g. "Engineering", "Design"
  learningPath?: string[]; // Steps/Resources
}

export interface CareerPath {
  roleId: string;
  roleTitle: string;
  matchScore: number; // 0-100
  missingSkills: { name: string; gap: number }[];
  learningResources: string[];
}

export interface CareerGoal {
  targetRoleId: string; // e.g., 'frontend-dev'
  targetRoleTitle: string;
  deadline?: string;
  customNotes?: string;
}